languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Home"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Corey Chen"
  image = "img/author.jpg"
  headline = "A developer who loves technology"
  bio = "Passionate about programming and technology sharing"
  links = [
    { github = "https://github.com/Larkspur-CY" },
  ]
