languageCode = "zh-Hans"
languageName = "简体中文"
languageDirection = "ltr"
weight = 2

title = "corey"

[params]
  dateFormat = "2006年1月2日"

[params.author]
  name = "Corey Chen"
  headline = "一个热爱技术的开发者"
  bio = "热爱编程和技术分享"
  links = [
    { github = "https://github.com/Larkspur-CY" },
  ]